base_frame: "base_"
fixed_frame: "world"
use_cloud_input: false
cloud_range_min: 0.1
cloud_range_max: 50.0
cloud_res: 0.05
kf_dist_linear: 0.10
kf_dist_angular: 0.174532925
use_imu: false
use_odom: false
use_vel: false
stamped_vel: false
publish_tf: false
publish_pose: true
publish_pose_stamped: true
publish_pose_with_covariance: false
publish_pose_with_covariance_stamped: true
position_covariance: [1e-9, 1e-9, 1e-9]
orientation_covariance: [1e-9, 1e-9, 1e-9]
max_angular_correction_deg: 45.0
max_linear_correction: 0.50
max_iterations: 10
epsilon_xy: 0.000001
epsilon_theta: 0.000001
max_correspondence_dist: 0.3
sigma: 0.010
use_corr_tricks: 1
restart: 0
restart_threshold_mean_error: 0.01
restart_dt: 1.0
restart_dtheta: 0.1
clustering_threshold: 0.25
orientation_neighbourhood: 20
use_point_to_line_distance: 1
do_alpha_test: 0
do_alpha_test_thresholdDeg: 20.0
outliers_maxPerc: 0.90
outliers_adaptive_order: 0.7
outliers_adaptive_mult: 2.0
do_visibility_test: 0
outliers_remove_doubles: 1
do_compute_covariance: 0
debug_verify_tricks: 0
use_ml_weights: 0
use_sigma_weights: 0
