name: Bridge
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      if: runner.os != 'Linux'

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push bridge
      env:
        DOCKER_CLI_AARCH64_IMAGE: docker.io/docker/cli:24.0.6-dind-aarch64
      run: |
        docker buildx build \
          --push --platform=linux/arm64,linux/amd64 \
          -t ericroboticsindia/cube_stack:bridge_latest \
          --file bridge.Dockerfile \
          .
          
    # - name: Build and push noetic
    #   env:
    #     DOCKER_CLI_AARCH64_IMAGE: docker.io/docker/cli:24.0.6-dind-aarch64
    #   run: |
    #     docker buildx build \
    #       --push --platform=linux/arm64,linux/amd64 \
    #       -t ericroboticsindia/cube_stack:noetic_latest \
    #       --file noetic.Dockerfile \
    #       .

    # - name: Build and push humble
    #   env:
    #     DOCKER_CLI_AARCH64_IMAGE: docker.io/docker/cli:24.0.6-dind-aarch64
    #   run: |
    #     docker buildx build \
    #       --push --platform=linux/arm64,linux/amd64 \
    #       -t ericroboticsindia/cube_stack:humble_latest \
    #       --file humble.Dockerfile \
    #       .

    
